@startuml
(*) --> "Двойной клик на папке"
if "Пользователь имеет права на чтение папки?" then
  --> [Права на чтения имеются] "Система загружает содержимое папки в текущую вкладку"
  --> "Содержимое папки отображается в программе"
else
  --> [Нет прав на чтение] "Система отображает сообщение об ошибке"
endif
@enduml