@startuml
(*) --> "Клик ПКМ на файл или папку"
--> "Клик ЛКМ на желаемое действие"
if "Пользователь имеет разрешения на выполнение действия?" then
  --> [Имеет] "Система выполняет изменение файловой системы"
  --> "Запрошенное действие с файлом/папкой выполнено"
else
  --> [Не имеет] "Система отображает сообщение об ошибке"
endif
@enduml