@startuml
(*) --> "Клик на строку поиска"
--> "Ввод частичного имени"
--> "Нажатие кнопки Enter"
if "Имя допустимое" then
  --> [Да] "Система сканирует папку рекурсивно и выводит найденные объекты на экран"
  --> "Все искомые файлы или папки выведены в окно отображения папки"
else
  --> [Нет] "Система отображает сообщение об ошибке"
endif
@enduml