@startuml
(*) --> "Клик на строку пути папки"
--> "Ввод пути к папке"
--> "Нажатие кнопки Enter"
if "Папка по введенному пути существует" then
  --> [Папка существует] "Система проверяет права на чтение папки"
  if "Пользователь имеет права на чтение папки?" then
    --> [Права на чтения имеются] "Система загружает содержимое папки в текущую вкладку"
    --> "Содержимое папки отображается в программе"
  else
    --> [Нет прав на чтение] "Система отображает сообщение об ошибке"
  endif
else
  --> [Папка не существует] "Система отображает сообщение об ошибке"
endif
@enduml