@startuml
(*) --> "Двойной клик по файлу"
if "Файл исполняемый (exe)?" then
  --> [Да] "Система запускает файл на выполнение"
  --> "Файл открыт"
else
  --> [Нет] "Система ищет подходящую программу для открытия файла"
  if "Программа для открытия найдена?" then
    --> [Да] "Система запускает найденную программу и передает ей путь к файлу"
    --> "Файл открыт"
  else
    --> [Нет] "Система открывает окно выбора программы, с помощью которой открыть файл"
    if "Пользователь выбрал программу" then
      --> [Да] "Система запускает выбранную программу и передает ей путь к файлу"
      --> "Файл открыт"
    else
      --> [Нет] "Файл не открыт"
    endif
  endif
endif
@enduml