@startuml
(*) --> "Клик ПКМ в свободном месте родительской папки"
--> "Клик ЛКМ 'Создать папку'"
--> "Система отображает диалоговое окно ввода имени папки"
--> "Пользователь вводит имя папки"
--> "Пользователь нажимает ОК"
if "Имя папки допустимое?" then
  --> [Имя папки допустимое] if "Есть права на запись в родительскую папку?" then
    --> [Права на запись имеются] "Система создает папку с указанным именем"
    --> "Папка создана"
  else
    --> [Нет прав на запись] "Система отображает сообщение об ошибке"
  endif
else
  --> [Имя папки недопустимое] "Система отображает сообщение об ошибке"
endif
@enduml