@startuml
(*) --> "Клик ПКМ в свободном месте папки"
--> "Клик ЛКМ 'Вид'"
--> "Клик ЛКМ 'Таблица'"
--> "Система меняет отображение папки на табличное"
--> "Клик ЛКМ на столбце таблицы, по которому будет идти сортировка"
--> "Система сортирует содержимое папки по заданному критерию"
--> "Содержимое папки отсортировано"
@enduml