@startuml

[*] --> СозданиеПапки : Нажал ЛКМ 'Создать папку'

state СозданиеПапки {
  [*] --> ВводИмени : Ввести имя папки
  ВводИмени --> ПроверкаИмяПапки : Подтверждение
  ВводИмени --> СозданиеПапки : Ошибка
  ПроверкаИмяПапки --> ПроверкаПраваНаЗапись : Подтверждение
  ПроверкаИмяПапки --> СозданиеПапки : Ошибка
  ПроверкаПраваНаЗапись --> СозданиеПапки : Подтверждение
  ПроверкаПраваНаЗапись --> СозданиеПапки : Ошибка
}

@enduml