@startuml

[*] --> ОткрытиеПапки : Нажал 'Enter'

state ОткрытиеПапки {
  [*] --> ПроверкаСуществованиеПапки : Открыть папку
  ПроверкаСуществованиеПапки --> ПроверкаПраваНаЧтение : Подтверждение
  ПроверкаСуществованиеПапки --> ОткрытиеПапки : Ошибка
  ПроверкаПраваНаЧтение --> ОткрытиеПапки : Подтверждение
  ПроверкаПраваНаЧтение --> ОткрытиеПапки : Ошибка
}

@enduml