@startuml

[*] --> ОткрытьФайл : Двойной клик по файлу

state ОткрытьФайл {
  [*] --> ИсполняемыйФайл : Проверка на исполняемость
  ИсполняемыйФайл --> ВыполнитьФайл : Запустить файл как программу
  ИсполняемыйФайл --> ПоискПрограммы : Найти программу для открытия файла
  ВыполнитьФайл --> ОткрытьФайл : Подтверждение
  ВыполнитьФайл --> ОткрытьФайл : Ошибка
  ПоискПрограммы --> ОткрытьФайлВПрограмме : Открыть в программе
  ПоискПрограммы --> ЗапросПрограммы : Спросить у пользователя программу
  ЗапросПрограммы --> ОткрытьФайлВПрограмме : Открыть в программе
  ЗапросПрограммы --> ОткрытьФайл : Не открывать
  ОткрытьФайлВПрограмме --> ОткрытьФайл : Подтверждение
  ОткрытьФайлВПрограмме --> ОткрытьФайл : Ошибка
}

@enduml